version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
      - SERVER_PORT=8761
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=true
      - EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS=30000
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
