server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-services
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
  circuitbreaker:
    resilience4j:
      instances:
        productClient:
          circuitbreaker:
            registerHealthIndicator: true
            enabled: true
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 10
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            eventConsumerBufferSize: 10
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
