server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
