version: '3.8'

services:
  product-services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=product-services
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=my-group-id
    depends_on:
      - eureka-server
      - api-gateway
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: productdb
    ports:
      - "3306:3306"

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway:latest
    ports:
      - "8080:8080"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
     image: confluentinc/cp-zookeeper:latest
     ports:
       - "2181:2181"
     environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000